<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \ArchiveDotOrg\Player\Block\
 */
 
 ?>
 
<div 
	style="position: fixed;bottom: 0;z-index: 999;width: inherit;background: #000;left: 0px;text-align: center;width:100%;"
	data-mage-init='{
	    "collapsible":{
	        "collapsible": true,
	        "openedState": "active",
	        "active": true 
	    }
	}'
id="major">
    <div data-role="title">
        <h4 style="margin-top:5px;margin-bottom:5px;cursor:pointer;color: #fff;background: #000;margin: 0px;padding: 5px;">Player</h4>
    </div>
    <div data-role="content">
        <div 
	 
	id="player">



<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div id="jp_container_1" class="jp-audio" role="application" aria-label="media player">
	<div class="jp-type-playlist">
		<div class="jp-gui jp-interface">
			<div class="jp-controls">
				<button class="jp-previous" role="button" tabindex="0">previous</button>
				<button class="jp-play" role="button" tabindex="0">play</button>
				<button class="jp-next" role="button" tabindex="0">next</button>
				<button class="jp-stop" role="button" tabindex="0">stop</button>
			</div>
			<div class="jp-progress">
				<div class="jp-seek-bar">
					<div class="jp-play-bar"></div>
				</div>
			</div>
			<div class="jp-volume-controls">
				<button class="jp-mute" role="button" tabindex="0">mute</button>
				<button class="jp-volume-max" role="button" tabindex="0">max volume</button>
				<div class="jp-volume-bar">
					<div class="jp-volume-bar-value"></div>
				</div>
			</div>
			<div class="jp-time-holder">
				<div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
				<div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
			</div>
			<div class="jp-toggles">
				<button class="jp-repeat" role="button" tabindex="0">repeat</button>
				<button class="jp-shuffle" role="button" tabindex="0">shuffle</button>
			</div>
		</div>
		<div class="jp-playlist">
			<ul>
				<li>&nbsp;</li>
			</ul>
		</div>
		<div class="jp-no-solution">
			<span>Update Required</span>
			To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
		</div>
	</div>
</div>

	<script type="text/x-magento-init">
	    {
	        "*": {
	            "ArchiveDotOrg_Player/js/player": {
	            	"playlist":[<?php echo $block->getPlaylist();?>]
	            } 
	        }
	    }
	</script>
    </div>
    </div>
</div>