<?php
use Magento\Framework\App\Action\Action;

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
$subcats = $category->getParentCategory()->getChildrenCategories();
?>
<!--div class="category-view category-view-on">
    <div class="category-image"><a href="<?php echo $category->getParentCategory()->getUrl();?>"><?php echo '<img src="'.$category->getParentCategory()->getImageUrl(). '" />';?></a></div>
</div-->
<style>
    .modal-popup .modal-inner-wrap{
        width:80%;
        margin:2rem auto;
    }
    .a-category-quicview-iframe{width:100%;}
    .toolbar.toolbar-products,
    header.page-header,
    footer.page-footer,
    .sections.nav-sections,
    .page-layout-1column .filter.block,
    .modal-header,.modal-footer,.copyright,.page-title-wrapper,.category-view{display:none;}
    .category-view-on{display:block !important;}
    .modal-popup .modal-content{padding:1rem !important;}
    .product-quickview {
        overflow: hidden;
        padding-top: 56.25%;
        position: relative;
    }
    .product-quickview iframe {
        border: 0;
        height: 100%;
        left: 0;
        position: absolute;
        top: 0;
        width: 100%;
    }
    .category-image{text-align:center;}
    .action.primary{background:#fff;color:#1979c3;}
</style>
<?if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <style>
        .plp-list-wrapper {
            display: grid;
            grid-template-columns: 20% 10% 11% 20% 13% 13% 13%;
            grid-gap: 10px;
            border-bottom:1px solid #999;
        }
        .plp-list-box {
            padding: 1%;
        }
        .plp-list-box-drop1-1{
            grid-column: 1 ;
            grid-row: 1/3;
        }
        .plp-list-box-drop1-2{
            grid-column: 2 ;
            grid-row: 1/3;
        }
        .plp-list-box-run3{
            grid-column: 3/8;
            grid-row: 2;
            font-size: 89%;
        }
        .product-item-inner-OFF .actions-primary,
        .product-item-inner-OFF .actions-secondary.product-item,
        .product-item-inner-OFF .actions-secondary.product-item a,
        .product-item-inner-OFF .add-to-links{float: left;display: inline-flex;width: inherit;}
    </style>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">

            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php 
            $_fix_me_artist = 1;
            $_artist_holder = '';
			$on_artist = '';
            $_fix_me_album = 1;
            $_album_holder = '';
			$on_album = '';
			$_fix_me_track = 1;
			$_track_holder = '';
			$on_track = '';
            foreach ($_productCollection as $_product):
			$on_artist = $_product->getAttributeText('artist');
			$on_album = substr($_product->getAttributeText('album_track'), stripos($_product->getAttributeText('album_track'),'_')+1);
			$on_album = substr($on_album, 0, strrpos($on_album,'_'));
            $on_track = substr($_product->getAttributeText('album_track'), strrpos($_product->getAttributeText('album_track'),'_')+1);
            if ($on_artist == $_artist_holder){
            	?>

            	<?php
            }elseif (($on_artist != $_artist_holder) && ($_fix_me_artist == 1)){
            	?>
				  	<!--h2><?php echo $on_artist;?></h2-->
				  	<div id="accordion-<?php echo preg_replace('/\W+/', '-', strtolower($on_album)); ?>" data-mage-init='{
				        "accordion":{
				            "active": "",
				            "collapsible": true,
				            "openedState": "active",
				            "multipleCollapsible": true
				        }}'>
				<?php
							$_artist_holder = $on_artist;			
							$_fix_me_artist = 0;	
			}else{
				$_fix_me_artist = 0;	
				$_artist_holder = $on_artist;										
				?>
					</div>
					<h2><?php echo $on_album;?></h2>
				  	<div id="accordion-<?php echo preg_replace('/\W+/', '-', strtolower($on_album)); ?>" data-mage-init='{
				        "accordion":{
				            "active": "",
				            "collapsible": true,
				            "openedState": "active",
				            "multipleCollapsible": true
				        }}'>
				        <h2></h2>
				<?php
			}
			
			
            if ($on_album == $_album_holder){
            	?>
            	
            	<?php
            }elseif (($on_album != $_album_holder) && ($_fix_me_album == 1)){
            	?>
				  	<h2><?php echo $on_album;?></h2>
				  	<div id="accordion-<?php echo preg_replace('/\W+/', '-', strtolower($on_album)); ?>" data-mage-init='{
				        "accordion":{
				            "active": "",
				            "collapsible": true,
				            "openedState": "active",
				            "multipleCollapsible": true
				        }}'>
				<?php
							$_album_holder = $on_album;			
							$_fix_me_album = 0;	
			}else{
				$_fix_me_album = 0;	
				$_album_holder = $on_album;										
				?>
					</div>
					<h2><?php echo $on_album;?></h2>
				  	<div id="accordion-<?php echo preg_replace('/\W+/', '-', strtolower($on_album)); ?>" data-mage-init='{
				        "accordion":{
				            "active": "",
				            "collapsible": true,
				            "openedState": "active",
				            "multipleCollapsible": true
				        }}'>
				        <h2></h2>
				<?php
			}
			
            
            
            if ($on_track == $_track_holder){
            	?>
            	
            	<?php
            }elseif (($on_track != $_track_holder) && ($_fix_me_track == 1)){ ?>
					<div data-role="collapsible">
				        <div data-role="trigger">
				            <span>Track #<?php echo $on_track;?> - <?php echo $_product->getTitle();?></span>
				        </div>
				    </div>
				    <div data-role="content">
						<ol style="padding:0px;">            
				            <li class="plp-list-wrapper">		            			            		            	
				            	<div class="plp-list-box"><strong></strong></div>
				            	<div class="plp-list-box"><strong>Length</strong></div>
				            	<div class="plp-list-box"><strong>Year</strong></div>
				            	<div class="plp-list-box"><strong>Venue</strong></div>		            	
				            	<div class="plp-list-box"><strong>Taper</strong></div>
				            	<div class="plp-list-box"><strong>Transferrer</strong></div>
				            	<div class="plp-list-box"><strong>Source</strong></div>
				            </li>	
							<?php
							$_track_holder = $on_track;			
							$_fix_me_track = 0;	
			}else{
				$_fix_me_track = 0;	
            	$_track_holder = $on_track;
				?>
					</ol>
				</div>
				<div data-role="collapsible">
				        <div data-role="trigger">
				            <span>Track #<?php echo $on_track;?> - <?php echo $_product->getTitle();?></span>
				        </div>
			    </div>
			    <div data-role="content">
					<ol>            
			            <li class="plp-list-wrapper">		            			            		            	
			            	<div class="plp-list-box"><strong></strong></div>
			            	<div class="plp-list-box"><strong>Length</strong></div>
			            	<div class="plp-list-box"><strong>Year</strong></div>
			            	<div class="plp-list-box"><strong>Venue</strong></div>		            	
			            	<div class="plp-list-box"><strong>Taper</strong></div>
			            	<div class="plp-list-box"><strong>Transferrer</strong></div>
			            	<div class="plp-list-box"><strong>Source</strong></div>
			            </li>					            
				<?php
			}
            
            ?>
            <li class="plp-list-wrapper">                
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <!--a class="plp-list-box plp-list-box-drop1-1" href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a-->
					<div class="plp-list-box">
                     <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
	                    <div class="product-item-inner-OFF">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Queue')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Queue') ?></span>
                                            </button>
                                        </form>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary product-item"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>                    
                    <div class="plp-list-box"><?php echo gmdate("H:i:s",$_product->getLength()); ?></div>
                    <div class="plp-list-box"><?php echo $_product->getAttributeText('show_year') ?></div>
                    <div class="plp-list-box"><?php echo $_product->getAttributeText('show_venue') ?></div>
                    <div class="plp-list-box"><?php echo $_product->getAttributeText('show_taper') ?></div>
                    <div class="plp-list-box"><?php echo $_product->getAttributeText('show_transferer') ?></div>
                    <div class="plp-list-box">Archive.org</div>                                        
            </li>
            <?php endforeach; ?>
        </ol>
    	</div>

   <?= $block->getToolbarHtml() ?>   
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>